# Generated by Django 5.0 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0025_motorevent_remove_motoreventrecord_parent_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentProcess',
            fields=[
                ('experiment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('experiment_name', models.CharField(max_length=100)),
                ('zinc_acetate_dosage_g', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dmac_dosage_ml', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('water_type', models.CharField(blank=True, max_length=50, null=True)),
                ('water_dosage_ml', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('heating_method', models.CharField(blank=True, max_length=50, null=True)),
                ('ph_adjust_config', models.CharField(blank=True, max_length=100, null=True)),
                ('solvent_ph', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('precursor_volume_ml', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('container_volume_ml', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('cleaning_solution_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cleaning_solution_volume_ml', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reaction_temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stirring_speed_rpm', models.IntegerField(blank=True, null=True)),
                ('stirring_duration_min', models.IntegerField(blank=True, null=True)),
                ('cool_down_rt_duration_min', models.IntegerField(blank=True, null=True)),
                ('drying_temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('drying_duration_h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
