# Generated by Django 5.0 on 2026-02-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0026_experimentprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], default='PENDING', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=128, null=True)),
                ('planned_parameters', models.JSONField(blank=True, default=dict)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=256, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRecipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=256, null=True)),
                ('dmac_dosage_ml', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('water_dosage_ml', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('solvent_ph', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reaction_temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stirring_speed_rpm', models.IntegerField(blank=True, null=True)),
                ('stirring_duration_min', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='main_page.materialtype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('material_type', 'version'), name='uq_material_recipe_version')],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step_no', models.IntegerField()),
                ('step_type', models.CharField(choices=[('DISPENSE', 'Dispense'), ('MOVE_ARM', 'Move Arm'), ('STIR', 'Stir'), ('HEAT', 'Heat'), ('WAIT', 'Wait'), ('SAMPLE', 'Sample'), ('CLEAN', 'Clean')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('expected_duration_sec', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main_page.materialrecipe')),
            ],
            options={
                'ordering': ['step_no', 'id'],
                'constraints': [models.UniqueConstraint(fields=('recipe', 'step_no'), name='uq_recipe_step_no')],
            },
        ),
        migrations.AddField(
            model_name='batchjob',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='main_page.materialrecipe'),
        ),
        migrations.CreateModel(
            name='BatchStepExecution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('command_payload', models.JSONField(blank=True, default=dict)),
                ('telemetry', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=256, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='main_page.batchjob')),
                ('recipe_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='main_page.recipestep')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CommandOutbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('ACKED', 'Acked'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_messages', to='main_page.batchjob')),
                ('step_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_messages', to='main_page.batchstepexecution')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryIngest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(blank=True, max_length=32, null=True)),
                ('device_id', models.CharField(blank=True, max_length=64, null=True)),
                ('topic', models.CharField(max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_records', to='main_page.batchjob')),
                ('step_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_records', to='main_page.batchstepexecution')),
            ],
        ),
    ]
