# Generated by Django 4.2.24 on 2026-06-10 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0028_characterization_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="逻辑标识，如 esp32_1", max_length=32, unique=True
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        blank=True,
                        help_text="MQTT Client ID，如 ESP32S3_xxx",
                        max_length=64,
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True,
                        help_text="硬件 MAC 地址，后续多设备区分用",
                        max_length=17,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='用户自定义别名，如 "反应釜 A"',
                        max_length=64,
                    ),
                ),
                ("is_registered", models.BooleanField(default=True)),
                ("is_online", models.BooleanField(default=False)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("busy", "Busy"),
                            ("estopped", "E-Stopped"),
                            ("offline", "Offline"),
                        ],
                        default="idle",
                        max_length=16,
                    ),
                ),
                ("current_task", models.JSONField(blank=True, default=dict)),
                ("telemetry", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "main_page_device",
                "ordering": ["device_id"],
            },
        ),
        migrations.AlterField(
            model_name="commandoutbox",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outbox_messages",
                to="main_page.batchjob",
            ),
        ),
        migrations.AlterField(
            model_name="commandoutbox",
            name="step_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outbox_messages",
                to="main_page.batchstepexecution",
            ),
        ),
        migrations.CreateModel(
            name="EmergencyStopLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("triggered_by", models.CharField(blank=True, max_length=64)),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        help_text="single / multi / broadcast",
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_by", models.CharField(blank=True, max_length=64)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estop_logs",
                        to="main_page.device",
                    ),
                ),
            ],
            options={
                "db_table": "main_page_emergency_stop_log",
                "ordering": ["-triggered_at"],
            },
        ),
    ]
