# Generated by Django 4.2.24 on 2026-07-16 06:48

import django.core.validators
from django.db import migrations, models


def set_motor_index(apps, schema_editor):
    Motor = apps.get_model('main_page', 'Motor')
    for motor in Motor.objects.all():
        motor.motor_index = max(0, motor.id - 1)
        motor.save(update_fields=['motor_index'])


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0029_device_alter_commandoutbox_job_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="motor",
            name="motor_index",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="对应 ESP32 的电机索引 0-3",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.RunPython(set_motor_index),
        migrations.AddField(
            model_name="spinning",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spinning",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="spinning",
            name="device_id",
            field=models.CharField(
                default="esp32_1",
                help_text="目标设备逻辑标识，如 esp32_1",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="spinning",
            name="dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spinning",
            name="error_message",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="spinning",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="spinning",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("busy", "Busy"),
                    ("estopped", "E-Stopped"),
                    ("offline", "Offline"),
                    ("error", "Error"),
                    ("completed", "Completed"),
                ],
                default="idle",
                max_length=16,
            ),
        ),
    ]
