# Generated by Django 4.2.24 on 2026-07-16 07:05

from django.db import migrations


MOTOR_NAME_MAP = {
    'Motor 1': 'Motor 0',
    'Motor 2': 'Motor 1',
    'Motor 3': 'Motor 2',
}


def rename_and_ensure_four_motors(apps, schema_editor):
    Motor = apps.get_model('main_page', 'Motor')

    # 将旧名称 Motor 1/2/3 重命名为与 ESP32 索引对应的 Motor 0/1/2
    for old_name, new_name in MOTOR_NAME_MAP.items():
        Motor.objects.filter(name=old_name).update(
            name=new_name,
            description=f'This is a spinning motor, index {new_name.split()[-1]}.',
        )

    # 补齐第四个电机（Motor 3 -> ESP32 index 3）
    existing_indices = set(Motor.objects.values_list('motor_index', flat=True))
    for index in range(4):
        if index not in existing_indices:
            Motor.objects.create(
                name=f'Motor {index}',
                motor_index=index,
                avaliable=True,
                description=f'This is a spinning motor, index {index}.',
            )

    # 同步历史 Spinning 记录中的 motor_name，避免旧任务找不到电机
    Spinning = apps.get_model('main_page', 'Spinning')
    for old_name, new_name in MOTOR_NAME_MAP.items():
        Spinning.objects.filter(motor_name=old_name).update(motor_name=new_name)


def reverse_rename_and_ensure_four_motors(apps, schema_editor):
    Motor = apps.get_model('main_page', 'Motor')
    reverse_map = {v: k for k, v in MOTOR_NAME_MAP.items()}

    for new_name, old_name in reverse_map.items():
        Motor.objects.filter(name=new_name).update(
            name=old_name,
            description=f'This is a spinning motor, ID {old_name.split()[-1]}.',
        )

    Spinning = apps.get_model('main_page', 'Spinning')
    for new_name, old_name in reverse_map.items():
        Spinning.objects.filter(motor_name=new_name).update(motor_name=old_name)


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0030_motor_motor_index_spinning_completed_at_and_more'),
    ]

    operations = [
        migrations.RunPython(
            rename_and_ensure_four_motors,
            reverse_code=reverse_rename_and_ensure_four_motors,
        ),
    ]
