# Generated by Django 4.2.24 on 2026-07-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0031_motor_rename_and_ensure_four"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motordata",
            name="motor_id",
            field=models.IntegerField(
                choices=[
                    (0, "Motor_0"),
                    (1, "Motor_1"),
                    (2, "Motor_2"),
                    (3, "Motor_3"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="motorevent",
            name="device_id",
            field=models.CharField(
                default="esp32_1",
                help_text="ESP32 设备逻辑标识，如 esp32_7cdfa1e6d3cc",
                max_length=32,
            ),
        ),
    ]
