# Generated by Django 4.2.24 on 2026-07-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0032_alter_motordata_motor_id_alter_motorevent_device_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="spinning",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spinning",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spinning",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("RUNNING", "Running"),
                    ("FINISHED", "Finished"),
                    ("FAILED", "Failed"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
