# Generated by Django 4.2.24 on 2026-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0033_spinning_finished_at_spinning_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spinning",
            name="motor_names",
            field=models.JSONField(
                blank=True, default=list, help_text="多电机调度时存储选中的电机名称列表"
            ),
        ),
    ]
